spring:
  datasource:
    target:
      url: jdbc:mysql://192.168.101.227:3307/demo?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useSSL=false&autoReconnect=true
      username: feeyo
      password: feeyo#1234
      driver-class-name: com.mysql.jdbc.Driver
  # redis 配置
  data:
    redisson:
      nodeAddresses:
        - redis://192.168.101.221:6479
      password: feeyo#1234
      timeout: 3000
      connectionPoolSize: 64
      connectionMinimumIdleSize: 10
      database: 2

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl